export const relatedPageOptions = [
  { title: 'Inspections — Overview', value: 'roof-inspections' },
  { title: 'Inspections — HAAG Certified Inspection', value: 'roof-inspections/haag-certified-inspection' },
  { title: 'Inspections — Pre-Purchase Roof Inspection', value: 'roof-inspections/pre-purchase-roof-inspection' },
  { title: 'Inspections — Pre-Listing Roof Inspection', value: 'roof-inspections/pre-listing-roof-inspection' },
  { title: 'Inspections — Storm & Wind Damage Inspection', value: 'roof-inspections/storm-and-wind-damage-inspection' },
  { title: 'Inspections — Annual Maintenance Inspection', value: 'roof-inspections/annual-maintenance-inspection' },

  { title: 'Services — Overview', value: 'services' },
  { title: 'Services — Roof Repair', value: 'services/roof-repair' },
  { title: 'Services — Roof Replacement & New Installation', value: 'services/roof-replacement-and-new-installation' },
  { title: 'Services — Residential Roofing', value: 'services/residential-roofing' },
  { title: 'Services — Commercial Roofing', value: 'services/commercial-roofing' },
  { title: 'Services — Gutter Installation & Repair', value: 'services/gutter-installation-and-repair' },

  { title: 'Materials — Overview', value: 'services/roofing-materials' },
  { title: 'Materials — Metal Roofing', value: 'services/roofing-materials/metal-roofing' },
  { title: 'Materials — Asphalt Shingle Roofing', value: 'services/roofing-materials/asphalt-shingle-roofing' },
  { title: 'Materials — Stone-Coated Steel Roofing', value: 'services/roofing-materials/stone-coated-steel-roofing' },
  { title: 'Materials — Tile Roofing', value: 'services/roofing-materials/tile-roofing' },
  { title: 'Materials — Slate Roofing', value: 'services/roofing-materials/slate-roofing' },

  { title: 'Problems — My Roof Is Leaking', value: 'roof-problems/my-roof-is-leaking' },
  { title: 'Problems — Storm Damage on My Roof', value: 'roof-problems/storm-damage-on-my-roof' },
  { title: 'Problems — My Roof Is at End of Life', value: 'roof-problems/my-roof-is-at-end-of-life' },
  { title: 'Problems — My Insurance Claim Was Denied', value: 'roof-problems/my-insurance-claim-was-denied' },
  { title: 'Problems — Buying or Selling a Home', value: 'roof-problems/buying-or-selling-a-home' },
  { title: 'Problems — Preparing for Hurricane Season', value: 'roof-problems/preparing-for-hurricane-season' },

  { title: 'Claims — Overview', value: 'claims' },
  { title: 'Claims — How the Claim Process Works', value: 'claims/how-the-claim-process-works' },
  { title: 'Claims — Denied or Underpaid Claims', value: 'claims/denied-or-underpaid-claims' },

  { title: 'Who We Serve — Homeowners', value: 'who-we-serve/homeowners' },
  { title: 'Who We Serve — Property Managers & AOAO / HOA Boards', value: 'who-we-serve/property-managers-aoao-hoa-boards' },
  { title: 'Who We Serve — General Contractors', value: 'who-we-serve/general-contractors' },
  { title: 'Who We Serve — Architects & Specifiers', value: 'who-we-serve/architects-and-specifiers' },
  { title: 'Who We Serve — Trustees & Estate Managers', value: 'who-we-serve/trustees-and-estate-managers' },

  { title: 'About — Our Story & Credentials', value: 'about/our-story' },
  { title: 'About — Project Gallery', value: 'about/gallery' },
  { title: 'About — Reviews', value: 'reviews' },
  { title: 'About — Blog', value: 'blog' },
  { title: 'Contact', value: 'contact' },
];
